packages:
  - apps/*
  - packages/*
  - tools/*

catalogMode: strict

catalog:
  '@dymo-api/better-auth': ^1.2.33
  '@oxlint/plugins': ^1.83.0
  '@types/node': ^26
  '@xcvzlabs/env': ^0.1.2
  better-auth: ^1.7.2
  drizzle-orm: 1.0.0-rc.5-5935859
  genbumppush: ^0.0.8
  typescript: ^6.0.3
  uuid: ^14.0.2
  valibot: ^1.5.0
  vite: npm:@voidzero-dev/vite-plus-core@1.0.0-rc.0
  vite-plus: 1.0.0-rc.0

catalogs:
  api:
    evlog: ^2.29.0
    handlebars: ^4.7.9
    h3: 2.0.1-rc.22
    nitro: 3.0.260610-beta
    unemail: ^0.7.0
  database:
    drizzle-kit: 1.0.0-rc.5-5935859
    drizzle-query-logger: ^1.1.2
    postgres: ^3.4.9
  web:
    '@formisch/vue': ^1.1.0
    '@golar/vue': ^0.1.10
    '@iconify-json/hugeicons': ^1.2.34
    '@iconify-json/lucide': ^1.2.132
    '@nuxt/cli': 4.0.0-alpha.0
    '@nuxtjs/better-auth': ^0.3.3
    '@nuxt/ui': ^4.11.1
    '@pinia/colada': ^1.4.4
    '@pinia/colada-nuxt': 1.1.0
    '@pinia/nuxt': 1.0.2
    '@vueuse/core': ^14.4.0
    '@vueuse/nuxt': ^14.4.0
    golar: ^0.1.10
    nuxt: ^4.5.2
    pinia: ^4.0.3
    pinia-plugin-persistedstate: ^4.7.1
    tailwindcss: ^4.3.3
    vue: ^3.5.41
    vue-router: ^5.3.1
    vue-tsc: ^3.3.11

overrides:
  '@nuxt/cli': alpha
  vite@*: 'catalog:'

peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: '*'

allowBuilds:
  esbuild: true
  vue-demi: true

minimumReleaseAgeExclude:
  - '@voidzero-dev/vite-plus-core@1.0.0-rc.0'
  - '@voidzero-dev/vite-plus-darwin-arm64@1.0.0-rc.0'
  - '@voidzero-dev/vite-plus-darwin-x64@1.0.0-rc.0'
  - '@voidzero-dev/vite-plus-linux-arm64-gnu@1.0.0-rc.0'
  - '@voidzero-dev/vite-plus-linux-arm64-musl@1.0.0-rc.0'
  - '@voidzero-dev/vite-plus-linux-x64-gnu@1.0.0-rc.0'
  - '@voidzero-dev/vite-plus-linux-x64-musl@1.0.0-rc.0'
  - '@voidzero-dev/vite-plus-win32-arm64-msvc@1.0.0-rc.0'
  - '@voidzero-dev/vite-plus-win32-x64-msvc@1.0.0-rc.0'
  - vite-plus@1.0.0-rc.0
