packages:
  - apps/*
  - packages/*
  - tools/*

catalogMode: strict

catalog:
  '@oxlint/plugins': ^1.83.0
  '@types/node': ^26
  genbumppush: ^0.0.8
  typescript: ^6.0.3
  vite: npm:@voidzero-dev/vite-plus-core@1.0.0-rc.0
  vite-plus: 1.0.0-rc.0

catalogs:
  api:
    nitro: 3.0.260903-beta

overrides:
  vite@*: 'catalog:'

peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: '*'
