packages:
  - apps/*
  - packages/*
  - tools/*

catalogMode: strict

catalog:
  '@oxlint/plugins': ^1.83.0
  '@types/node': ^26
  '@better-auth/api-key': ^1.7.6
  '@xcvzlabs/env': ^0.1.2
  better-auth: ^1.7.6
  genbumppush: ^0.0.8
  lru-cache: ^11.1.0
  typescript: ^6.0.3
  unemail: 0.7.0
  uuid: ^14.0.2
  valibot: ^1.5.0
  vite: npm:@voidzero-dev/vite-plus-core@1.0.0-rc.0
  vite-plus: 1.0.0-rc.0

catalogs:
  api:
    nitro: 3.0.260903-beta
  database:
    drizzle-orm: 1.0.0-rc.5-5935859
    drizzle-kit: 1.0.0-rc.5-5935859
    postgres: ^3.4.9

overrides:
  vite@*: 'catalog:'

peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: '*'

allowBuilds:
  esbuild: true
